version: 2

project_name: lazy-k8s

before:
  hooks:
    - go mod tidy

builds:
  - id: lazy-k8s
    main: ./cmd/lazy-k8s
    binary: lazy-k8s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: lazy-k8s
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"

nfpms:
  - id: lazy-k8s
    package_name: lazy-k8s
    homepage: "https://github.com/Starlexxx/lazy-k8s"
    description: "A terminal UI for Kubernetes management"
    maintainer: "lazy-k8s maintainers"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
